queue: 'Hosted Linux Preview'

variables:
  buildConfiguration: 'Release'

steps:

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**/*[Tt]ests/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: pack
      packagesToPack: 'src/SignalR.Orleans/*.csproj'
      packDirectory: '$(build.artifactStagingDirectory)'
      configuration: '$(buildConfiguration)'
      versioningScheme: byEnvVar
      versionEnvVar: Version

  - task: DotNetCoreCLI@2
    inputs:
      command: push
      packagesToPush: '$(build.artifactStagingDirectory)/*.nupkg'
      publishFeedCredentials: 'OSS'
      nuGetFeedType: external
      versioningScheme: byEnvVar
      versionEnvVar: Version
